DECLARE @str NVARCHAR(1024) = N'\\tmnt.corp\sqlbackups\ADBackSQL\trn\ADBack\ADBack_'+REPLACE(CONVERT(NVARCHAR(20),GETDATE(),102),'.','_')+'_'+REPLACE(CONVERT(NVARCHAR(20),GETDATE(),114),':','_')+'.trn';

BACKUP LOG ADBack
TO DISK = @str
WITH INIT,STATS=5,COMPRESSION
